version: '1.0'

services:
  ytc-client:
    image: ytc-frontend
    stdin_open: true
    ports:
      - "3000:80"
    networks:
      - app
    build:
      context: ./frontend
      dockerfile: Dockerfile

  ytc-server:
    image: ytc-backend
    stdin_open: true
    ports:
      - "5000:80"
    networks:
      - app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - app
    volumes:
      - mongo-data:/data/db

networks:
  app:
    driver: bridge
volumes:
  mongo-data:
    driver: local